name: Benchmark all solutions

on: workflow_dispatch

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Benchmark
        run: go test -run=^$ -bench=. -benchmem ./...
